spring.application.name=productoservice

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.data.mongodb.uri=mongodb://admin:admin123@host.docker.internal:27017/admin