spring.application.name=productoservice

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.data.mongodb.uri=mongodb+srv://ceviche:cevicheContrase%C3%B1a@cluster0.eix4rmi.mongodb.net/tareadb?retryWrites=true&w=majority&appName=Cluster0

# Bootstrap server - usa kafka:29092 en Docker, localhost:9092 en local
spring.kafka.bootstrap-servers=kafka:29092

# --- Producer ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.productos=productos-topico

# Forzar a Kafka a fallar rápido si no hay red (3000 ms = 3 segundos)
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=3000